### ISSUE TITLE
zurl rejects OPTIONS requests with a body against spec

### ISSUE THREAD

**Issue by charliewolf** [fanout/zurl#10]
Per rfc2616: ```If the OPTIONS request includes an entity-body (as indicated by the presence of Content-Length or Transfer-Encoding), then the media type MUST be indicated by a Content-Type field. Although this specification does not define any use for such a body, future extensions to HTTP might use the OPTIONS body to make more detailed queries on the server. A server that does not support such an extension MAY discard the request body.```

**Comment by jkarneges** [comment]
Thanks for the report! Fixed in 14ae1322b108ad51675bd40d878830f203e6a972

**Comment by charliewolf** [comment]
@jkarneges thanks! when can we expect a new zurl release with this fix in place?

**Comment by jkarneges** [comment]
@charliewolf within a few days
