### ISSUE TITLE
wsecho example undefined-condition

### ISSUE THREAD

**Issue by tmestdagh** [fanout/zurl#14]
Hi, I am trying to get the wsecho.py example working but I am running into an issue.

I am running the example like this 

`python tools/wsecho.py wss://echo.websocket.org`

and this is the output that I am receiving

```
OUT: {'credits': 200000, 'from': 'wsecho.py', 'id': '91eaff57-22a4-437b-adf4-dc87370128fb', 'seq': 0, 'uri': 'wss://echo.websocket.org'}
IN: {'from': '{e38917b3-369f-419f-90f3-fb75300dc714}', 'type': 'error', 'id': '91eaff57-22a4-437b-adf4-dc87370128fb', 'condition': 'undefined-condition', 'seq': 0L}
```

**Comment by jkarneges** [comment]
Well that's a great bug. It seems the trailing slash is needed for domain-only URLs. This works for me:

```
python tools/wsecho.py wss://echo.websocket.org/
```

I'll fix it so this isn't needed.

**Comment by tmestdagh** [comment]
Ha, can't believe I didn't try that!  :smiley: 

I can verify that it works with the trailing /

Thanks
