### ISSUE TITLE
Sending data in body

### ISSUE THREAD

**Issue by jonaslejon** [fanout/zurl#16]
Hello,

I'm trying to send some body data from PHP like this:

$ php zeromq-send.php
Sending
{"method":"POST","uri":"https:\/\/xxx.se\/delay.php","body":"HELLO"}

But the body content HELLO won't show up in the POST-data on the server. What am I doing wrong?

**Comment by jkarneges** [comment]
Works for me.

Simple python program:
```py
import tnetstring
import zmq

ctx = zmq.Context()
sock = ctx.socket(zmq.REQ)
sock.connect('ipc:///tmp/zurl-req')

req = {
    'method': 'POST',
    'uri':    'http://localhost:8000',
    'body':   'hello\n'
}
sock.send('T' + tnetstring.dumps(req))

resp = tnetstring.loads(sock.recv()[1:])
print('{}'.format(resp))
```

Receive with netcat:
```sh
$ nc -l 8000
POST / HTTP/1.1
Host: localhost:8000
Accept: */*
Accept-Encoding: deflate, gzip
Content-Length: 6

hello
```

**Comment by jonaslejon** [comment]
Thanks @jkarneges. Found the problem, the test-server was saving the request in with the $_POST array. And somehow the request would not show up in the array
