### ISSUE TITLE
Debian package available on fanout repository is broken for stretch

### ISSUE THREAD

**Issue by grignards** [fanout/zurl#19]
The stretch package available on https://dl.bintray.com/fanout/ requires `libcurl4` which is not available (only `libcurl3` is).

zurl package version: 1.11.0-1~bp9 (`libcurl4` dependency was added in 1.10 if I'm right).

**Comment by jannic** [comment]
Thanks for the report. The dependency on libcurl4 was indeed wrong for the stretch package.
Fixed in 1.11.0-1~bp9.1 (https://dl.bintray.com/fanout/debian/pool/z/zurl/:zurl_1.11.0-1~bp9.1_amd64.deb)

**Comment by grignards** [comment]
Thank you for the fix.
